apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcalc-deployment
  namespace: tp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devcalc
  template:
    metadata:
      labels:
        app: devcalc
    spec:
      containers:
        - name: devcalc-api
          image: nicolasmmartins/devcalc-api:latest
          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5