apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-svc
  namespace: tp2
spec:
  type: ClusterIP
  selector:
    app: nginx-test
  ports:
    - name: http
      port: 8081       # porta exposta no cluster
      targetPort: 80   # porta real do container NGINX