apiVersion: v1
kind: Service
metadata:
  name: devcalc-nodeport
  namespace: tp2
spec:
  type: NodePort
  selector:
    app: devcalc
  ports:
    - port: 8080         # porta interna do service
      targetPort: 8080   # porta do container
      nodePort: 30003    # porta exposta externamente
      protocol: TCP